version: '3'
services:
  prometheus:
    image: prom/prometheus:v2.50.1
    ports:
      - "9090:9090" # Prometheus Main port
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
      - --query.lookback-delta=30s
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus-data:/prometheus

  grafana:
    image: grafana/grafana:10.3.4
    ports:
     - "3000:3000" # Admin UI
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/datasources/
      - ./grafana/dashboards-config/:/etc/grafana/provisioning/dashboards/
      - ./grafana/dashboards-json/:/etc/dashboards/
      - ./grafana-data:/var/lib/grafana

  loki:
    image: grafana/loki:2.9.2
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki.yml
    volumes:
      - ./loki.yml:/etc/loki/loki.yml
      - ./loki-data:/tmp/loki

  tempo:
    image: grafana/tempo:2.4.0
    command: [ "-config.file=/etc/tempo.yml" ]
    volumes:
      - ./tempo.yml:/etc/tempo.yml
      - ./tempo-data:/tmp/tempo
    ports:
      - "14268"  # jaeger ingest
      - "3200"   # tempo
      - "4317"  # otlp grpc
      - "4318"  # otlp http
      - "9411"   # zipkin

# Need to be install on HRMS server
  promtail:
    image: grafana/promtail:2.9.2
    command: -config.file=/etc/promtail/promtail.yml
    volumes:
      - ./promtail.yml:/etc/promtail/promtail.yml

  agent:
    image: grafana/agent:v0.40.2
    volumes:
      - ./agent.yml:/etc/agent.yml
    command: -config.file=/etc/agent.yml

  # elasticsearch:
  #   image: elasticsearch:7.17.18
  #   container_name: es
  #   environment:
  #     discovery.type: single-node
  #     ES_JAVA_OPTS: "-Xms512m -Xmx512m"
  #   ports:
  #     - "9200:9200"
  #     - "9300:9300"
  #   healthcheck:
  #     test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
  #     interval: 10s
  #     timeout: 10s
  #     retries: 3

  # logstash:
  #   image: logstash:7.17.18
  #   container_name: log
  #   environment:
  #     discovery.seed_hosts: logstash
  #     LS_JAVA_OPTS: "-Xms512m -Xmx512m"
  #   volumes:
  #     - ./logstash/pipeline/logstash-nginx.config:/usr/share/logstash/pipeline/logstash-nginx.config
  #     - ./logstash/nginx.log:/home/nginx.log
  #   ports:
  #     - "5001:5000"
  #     - "5044:5044"
  #     - "9600:9600"
  #   depends_on:
  #     - elasticsearch
  #   command: logstash -f /usr/share/logstash/pipeline/logstash-nginx.config

  # kibana:
  #   image: kibana:7.17.18
  #   container_name: kib
  #   ports:
  #     - "5601:5601"
  #   depends_on:
  #     - elasticsearch

  # cadvisor:
  #   image: google/cadvisor:v0.33.0
  #   ports:
  #    - "8081:8080" # Port for prometheus to pull metrics

  # node_exporter:
  #   image: prom/node-exporter:v1.6.1
  #   ports:
  #    - "9100:9100" # Port for prometheus to pull metrics

  # graphite_exporter:
  #   image: prom/graphite-exporter:v0.14.0
  #   ports:
  #    - "9108:9108" # Port for listen incoming graphite plaintext protocol
  #    - "9109:9109" # Port for prometheus to pull metrics

  # graphite:
  #   image: graphiteapp/graphite-statsd:1.1.10-5
  #   ports:
  #     - "80:80" # Admin UI
  #     - "8080:8080" # Port for Grafana to use
  #     - "2003:2003" # carbon receiver - plaintext
  #     - "2004:2004" # carbon receiver - pickle
  #     - "2023:2023" # carbon aggregator - plaintext
  #     - "2024:2024" # carbon aggregator - pickle
  #     - "8126:8126" # Statsd Admin
  #     - "8125:8125" # Statsd
