version: '3'
services:
  cadvisor:
    image: google/cadvisor:v0.33.0
    ports:
     - "8081:8080" # Port for prometheus to pull metrics
  node_exporter:
    image: prom/node-exporter:v1.6.1
    ports:
     - "9100:9100" # Port for prometheus to pull metrics
  graphite_exporter:
    image: prom/graphite-exporter:v0.14.0
    ports:
     - "9108:9108" # Port for listen incoming graphite plaintext protocol
     - "9109:9109" # Port for prometheus to pull metrics
  prometheus:
    image: prom/prometheus:v2.47.2
    ports:
      - "9090:9090" # Prometheus Main port
    volumes:
      - ./prometheus/:/etc/prometheus/
  graphite:
    image: graphiteapp/graphite-statsd:1.1.10-5
    ports:
      - "80:80" # Admin UI
      - "8080:8080" # Port for Grafana to use
      - "2003:2003" # carbon receiver - plaintext
      - "2004:2004" # carbon receiver - pickle
      - "2023:2023" # carbon aggregator - plaintext
      - "2024:2024" # carbon aggregator - pickle
      - "8126:8126" # Statsd Admin
      - "8125:8125" # Statsd
    volumes:
      - ./prometheus/:/etc/prometheus/
  grafana:
    image: grafana/grafana:10.2.0
    ports:
     - "3000:3000" # Admin UI
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/datasources/
      - ./grafana/dashboards-config/:/etc/grafana/provisioning/dashboards/
      - ./grafana/dashboards-json/:/etc/dashboards/
