version: '3'
services:
  prometheus:
    image: prom/prometheus:v2.50.1
    ports:
      - "9090:9090" # Prometheus Main port
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
      - --query.lookback-delta=30s
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus-data:/prometheus

  grafana:
    image: grafana/grafana:10.3.4
    ports:
     - "3000:3000" # Admin UI
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/datasources/
      - ./grafana/dashboards-config/:/etc/grafana/provisioning/dashboards/
      - ./grafana/dashboards-json/:/etc/dashboards/
      - ./grafana-data:/var/lib/grafana

  loki:
    image: grafana/loki:2.9.2
    ports:
      - "3100:3100"
      - "9096:9096"
    command: [ "-config.file=/etc/loki/loki.yml" ]
    volumes:
      - ./loki.yml:/etc/loki/loki.yml
      - ./loki-data:/loki

  tempo:
    image: grafana/tempo:2.4.0
    command: [ "-config.file=/etc/tempo.yml" ]
    volumes:
      - ./tempo.yml:/etc/tempo.yml
      - ./tempo-data:/tmp/tempo
    ports:
      - "14268"  # jaeger ingest
      - "3200"   # tempo
      - "4317"  # otlp grpc
      - "4318"  # otlp http
      - "9411"   # zipkin
