apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
  # - name: Graphite
  #   type: graphite
  #   access: proxy
  #   url: http://graphite:8080
  #   jsonData:
  #     graphiteVersion: '1.1'
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    basicAuth: false
    isDefault: true
    version: 1
